// <auto-generated />
using EK_KM_webaruhaz_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EK_KM_webaruhaz_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316132431_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EK_KM_webaruhaz_API.Model.Termek", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("gyarto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("mennyiseg")
                        .HasColumnType("int");

                    b.Property<string>("tech_adat_1")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tech_adat_2")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tech_adat_3")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("termek_ara")
                        .HasColumnType("int");

                    b.Property<string>("termek_leirasa")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("termek_neve")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("tipus")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("Termek");
                });
#pragma warning restore 612, 618
        }
    }
}
